### ISSUE TITLE
MacOS Sierra requires charlock_holmes 0.7.5

### ISSUE THREAD

**Issue by Jesus89** [gfiorav/carto_loves_mac#12]
In CartoDB > "bundle install" there is an error when charlock_holmes is installed. It can not build native gems.

I have updated the "charlock_holmes" gem version in the Gemfile to 0.7.5 and it works perfectly.

**Comment by gfiorav** [comment]
Hi!

Thanks for opening the issue. 

Could you post some specifics about your system? I installed `charlock_holmes` with no issues. I'd much rather not modify the Gemfile.

An output of `uname -a` should suffice.

Thanks!

**Comment by Jesus89** [comment]
MacBook-Air-de-CARTO:~ cartotemporal$ uname -a
Darwin MacBook-Air-de-CARTO.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Comment by gfiorav** [comment]
After in person conversation we're closing this. It looks like some dep. issue. 

Thanks!

**Comment by nobuti** [comment]
FYI `gem install charlock_holmes -v 0.7.2 -- --with-cxxflags=-std=c++11` worked for me.
